version: '3.5'
services:
  # macula:
  #   image: anagolay/macula:bb1929a
  #   environment:
  #     - IPFS_GATEWAY_URL=http://ipfs:8080
  #     - IPFS_API_URL=http://ipfs:5001/api/v0
  #     - REDIS_URL=redis://redisCache
  #     - KELP_MACULA_ENV=docker:dev-build
  #     - MACULA_LOG_LEVEL=trace
  #     - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN
  #   links:
  #     - ipfs
  #     - redisCache
  #   depends_on:
  #     ipfs:
  #       condition: service_started
  #     redisCache:
  #       condition: service_started
  #   ports:
  #     - 3000:3000
  redis:
    image: redislabs/redismod:latest
    # command: --dir /data --loadmodule /usr/lib/redis/modules/rejson.so
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
  mongodb:
    image: docker.io/mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  ipfs:
    image: ipfs/kubo:master-2022-09-19-32e9a69
    environment:
      - IPFS_PROFILE=server
    ports:
      - 4001:4001 # ipfs swarm - expose if needed/wanted
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8080:8080 # ipfs gateway - expose if needed/wanted
    volumes:
      - ipfs_data:/data/ipfs
      - ./ipfs_upload:/data/upload

volumes:
  mongodb_data:
  ipfs_data:
  anagolay_data:
  redis_data:
