x-macula-links:
  &macula_links
  links:
    - ipfs
    - redis
    - mongodb
x-macula-dependson:
  &macula_dependson
  depends_on:
    ipfs:
      # condition: service_healthy
      condition: service_started
    redis:
      condition: service_started
    mongodb:
      condition: service_started
x-macula:
  &macula
  image: registry.gitlab.com/kelp_digital/oss/macula:d48f7379
  restart: unless-stopped
  networks:
    - macula
    - caddy
####################
####################
####################
####################
####################
version: '3'
services:
  maculaSubdomainHosting:
    <<: *macula
    <<: *macula_links
    <<: *macula_dependson
    labels:
      caddy: "*.macula.link"
      caddy.rewrite: "* /hosting/withSubdomain/{labels.2}{uri}}"
      caddy.reverse_proxy.to: "{{upstreams 3000}}"
      caddy.tls.dns: "hetzner ${HETZNER_TOKEN}"
      caddy.log: ""
      caddy.log.output: "file /var/logs/macula/subdomain.log"
      caddy.log.level: "DEBUG"
    environment:
      - MACULA_ENABLED_ROUTES=["hosting"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin

  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    networks:
      - macula
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'ipfs dag stat /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn || exit 1'
        ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    command: daemon --enable-namesys-pubsub
  redis:
    image: docker.io/redis:alpine
    networks:
      - macula
    command: redis-server
    volumes:
      - redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
  mongodb:
    image: docker.io/mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
networks:
  macula:
    driver: bridge
  caddy:
    external: true
volumes:
  ipfs_data: {}
  ipfs_fuse: {}
  ipns_fuse: {}
  redis_data: {}
  mongodb_data: {}
