x-macula-links: &macula_links
  links:
    - ipfs
    - redis
    - mongodb
x-macula-depends_on: &macula_depends_on
  depends_on:
    ipfs:
      # condition: service_healthy
      condition: service_started
    redis:
      condition: service_started
    mongodb:
      condition: service_started
x-macula: &macula
  image: kelpdigital/macula:a0532dd
  # image: registry.gitlab.com/kelp_digital/oss/macula:39d22195
  restart: unless-stopped
  networks:
    - macula_ipfs
    - caddy

####################
####################
####################
####################
####################
version: '3'
services:
  macula_website:
    image: kelpdigital/macula:a0532dd
    restart: unless-stopped
    networks:
      - macula_ipfs
      - caddy
    <<: *macula_depends_on
    links:
      - ipfs
      - redis
      - mongodb
    labels:
      caddy: 'macula.link'
      caddy.rewrite: '* /hosting/withSubdomain/macula{uri}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.log.output: 'file /var/logs/macula/macula.link.log'
      caddy.log.level: 'DEBUG'
    environment:
      - MACULA_ENABLED_ROUTES=["hosting"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis:6379
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin

  macula_ipfs_api:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES=["ipfs_api"]
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - IPFS_API_URL=http://ipfs:5001
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: 'api.ipfs.macula.link'
      caddy.rewrite: '* /ipfs_api{uri}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      # caddy.reverse_proxy.flush_interval: "-1"
      caddy.reverse_proxy.buffer_requests: '1'
      caddy.log.output: 'file /var/logs/macula/ipfs_api.log'
      caddy.log.level: 'DEBUG'

  macula_ipfs_image_processing_and_gateway:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES=["image_processing"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: 'ipfs.macula.link'
      # caddy.rewrite: '* /ipfs/{labels.2}{uri}}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.log.output: 'file /var/logs/macula/ipfs_gateway.log'
      caddy.log.level: 'DEBUG'

  macula_subdomain_star:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES=["hosting"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: '*.macula.link'
      caddy.rewrite: '* /hosting/withSubdomain/{labels.2}{uri}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.tls.dns: 'hetzner ${HETZNER_TOKEN}'
      caddy.log.output: 'file /var/logs/macula/subdomain.log'
      caddy.log.level: 'DEBUG'

  macula_cid_star:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES=["hosting"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: '*.on.macula.link'
      caddy.rewrite: '* /hosting/withIpfs/{labels.3}{uri}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.tls.dns: 'hetzner ${HETZNER_TOKEN}'
      caddy.log.output: 'file /var/logs/macula/cid_star.log'
      caddy.log.level: 'DEBUG'

  macula_hosting_api:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES=["hosting"]
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - IPFS_API_URL=http://ipfs:5001
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: 'api.macula.link'
      caddy.rewrite: '* /hosting/api{uri}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.log.output: 'file /var/logs/macula/hosting_api.log'
      caddy.log.level: 'DEBUG'

  redis:
    image: redislabs/redismod:latest
    networks:
      - macula_ipfs
    volumes:
      - redis_data:/data
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  ipfs:
    image: ipfs/kubo:master-2022-09-19-32e9a69
    # image: ipfs/go-ipfs:latest
    networks:
      - macula_ipfs
      - external_ipfs
    restart: unless-stopped
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    healthcheck:
      test: ['CMD-SHELL', 'ipfs dag stat /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn || exit 1']
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./ipfs_data_upload:/data/upload
    command: daemon --enable-namesys-pubsub
  mongodb:
    image: docker.io/mongo:latest
    networks:
      - macula_ipfs
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    volumes:
      - mongodb_data:/data/db
    # ports:
    # - 27017:27017

networks:
  external_ipfs:
    driver: bridge
  macula_ipfs:
    internal: true
    # driver: bridge
  caddy:
    external: true
volumes:
  ipfs_data: {}
  ipfs_fuse: {}
  ipns_fuse: {}
  redis_data: {}
  mongodb_data: {}
