x-macula-links: &macula_links
  links:
    - ipfs
    - redis
    - mongodb
x-macula-depends_on: &macula_depends_on
  depends_on:
    ipfs:
      # condition: service_healthy
      condition: service_started
    redis:
      condition: service_started
    mongodb:
      condition: service_started
x-macula: &macula
  image: docker.io/node:18.4.0-bullseye
  restart: unless-stopped
  working_dir: /app
  volumes:
    - ../../:/app
  networks:
    - macula
    - caddy
  environment:
    - IPFS_GATEWAY_URL=http://ipfs:8080
    - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
    - REDIS_URL=redis://redis
    - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
    - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin

####################
####################
####################
####################
####################
version: '3'
services:
  macula_website:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    labels:
      caddy: 'macula.link'
      caddy.rewrite: '* /hosting/withSubdomain/macula{uri}}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.log.output: 'file /var/logs/macula/link.sub.log'
      caddy.log.level: 'DEBUG'

  macula_ipfs_api:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES='["ipfs_api"]'
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: 'ipfs.api.macula.link'
      caddy.rewrite: '* /ipfs_api/{labels.2}{uri}}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.log.output: 'file /var/logs/macula/ipfs_api.log'
      caddy.log.level: 'DEBUG'

  macula_subdomain_star:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES='["hosting"]'
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: '*.macula.link'
      caddy.rewrite: '* /hosting/withSubdomain/{labels.2}{uri}}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.tls.dns: 'hetzner ${HETZNER_TOKEN}'
      # caddy.log: ""
      caddy.log.output: 'file /var/logs/macula/subdomain.log'
      caddy.log.level: 'DEBUG'

  macula_cid_star:
    <<: *macula
    <<: *macula_links
    <<: *macula_depends_on
    environment:
      - MACULA_ENABLED_ROUTES='["hosting"]'
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - IPFS_CACHE_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis
      - DOPPLER_TOKEN=$DOPPLER_MACULA_TOKEN_STAGING
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    labels:
      caddy: '*.on.macula.link'
      caddy.rewrite: '* /hosting/withIpfs/{labels.2}{uri}}'
      caddy.reverse_proxy.to: '{{upstreams 3000}}'
      caddy.tls.dns: 'hetzner ${HETZNER_TOKEN}'
      # caddy.log: ""
      caddy.log.output: 'file /var/logs/macula/cid_star.log'
      caddy.log.level: 'DEBUG'

  ipfs:
    image: ipfs/kubo:master-2022-09-19-32e9a69
    restart: unless-stopped
    networks:
      - macula
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    healthcheck:
      test: ['CMD-SHELL', 'ipfs dag stat /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn || exit 1']
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    command: daemon --enable-namesys-pubsub
  redis:
    image: redislabs/redismod:latest
    networks:
      - macula
    command: redis-server
    volumes:
      - redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    # ports:
    # - 6379:6379
  mongodb:
    image: docker.io/mongo:latest
    networks:
      - macula
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGODB_CONNSTRING_WITH_DB=mongodb://admin:123456@mongodb:27017/macula?authSource=admin
    volumes:
      - mongodb_data:/data/db
    # ports:
    # - 27017:27017
networks:
  macula:
    internal: true
  caddy:
    external: true
volumes:
  ipfs_data: {}
  ipfs_fuse: {}
  ipns_fuse: {}
  redis_data: {}
  mongodb_data: {}
