// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Add the item to the ipfs
 * @public
 */
// eslint-disable-next-line @typescript-eslint/naming-convention
export interface Add {
  /**
   * Chunking algorithm, size-[bytes], rabin-[min]-[avg]-[max] or buzhash.
   * Default: size-262144. Required: no.
   */
  chunker?: string;

  /**
   * CID version. Defaults to 0 unless an option that depends on CIDv1 is
   * passed.
   */
  'cid-version'?: number;

  /**
   * Check the filestore for pre-existing blocks. (experimental). Required: no.
   */
  fscache?: boolean;

  /**
   * Hash function to use. Implies CIDv1 if not sha2-256. (experimental).
   * Default: sha2-256. Required: no.
   */
  hash?: string;

  /**
   * Inline small blocks into CIDs. (experimental). Required: no.
   */
  inline?: boolean;

  /**
   * Maximum block size to inline. (experimental). Default: 32. Required: no.
   */
  'inline-limit'?: number;

  /**
   * Add the file using filestore. Implies raw-leaves. (experimental). Required:
   * no.
   */
  nocopy?: boolean;

  /**
   * Only chunk and hash - do not write to disk. Required: no.
   */
  'only-hash'?: boolean;

  /**
   * Pin this object when adding. Default: true. Required: no.
   */
  pin?: boolean;

  /**
   * Stream progress data. Required: no.
   */
  progress?: boolean;

  /**
   * Write minimal output. Required: no.
   */
  quiet?: boolean;

  /**
   * Write only final hash. Required: no.
   */
  quieter?: boolean;

  /**
   * Use raw blocks for leaf nodes. Required: no.
   */
  'raw-leaves'?: boolean;

  /**
   * Write no output. Required: no.
   */
  silent?: boolean;

  /**
   * Use trickle-dag format for dag generation. Required: no.
   */
  trickle?: boolean;

  /**
   * Wrap files with a directory object. Required: no.
   */
  'wrap-with-directory'?: boolean;
}
