# We want to build this separately because the sveltekit breaks all the time
build-macula-app:
  needs: ['test-code']
  allow_failure: true
  stage: build
  when: manual
  extends:
    - .install-pnpm-and-node
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    - echo 'Building and testing all packages...'
    - node common/scripts/install-run-rush.js build --from @kelp_digital/macula_app

    - echo 'Building Macula app ...'
    - cd ./app
    - pnpm build:vite
