build:
  extends:
    - .install-pnpm-and-node
  stage: build
  needs: ['is-it-pretty', 'changelogs']
  script:
    - !reference [.rush:install, script]
    - !reference [.rush:build, script]

    - echo 'Building Macula app ...'
    - cd ./app
    - pnpm build:vite
