build_app:
  extends:
    - .install-pnpm-and-node
  stage: build
  needs: ['is-it-pretty', 'changelogs', 'retest']
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ./app/src/*.{ts, css, svelte, html, d.ts} # ...source files
  script:
    # - !reference [.rush:install, script]
    # build the deps
    - !reference [.rush:build, script]

    - echo 'Building Macula app ...'
    - cd ./app
    - pnpm build:app

build_ui-components:
  extends:
    - .install-pnpm-and-node
  stage: build
  needs: ['is-it-pretty', 'changelogs', 'retest']
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ./ui-packages/svelte-ui-components/src/*.{ts, css, svelte, html, d.ts} # ...source files
  script:
    # - !reference [.rush:install, script]
    # build the deps
    - !reference [.rush:build, script]

    - echo 'Building UI components demo app ...'
    - cd ./ui-packages/svelte-ui-components
    - pnpm build:app
