publish-to-anagolay-registry:
  extends:
    - .install-pnpm-and-node
  stage: publish
  needs: ['is-it-pretty', 'changelogs', 'retest']
  # cache: {}
  allow_failure: true
  when: manual
  script:
    - set e
    - !reference [.rush:install, script]
    - !reference [.rush:retest, script]

    - git config --local user.email kelpbot@noreply.kelp.digital
    - git config --local user.name KelpBot

    - node common/scripts/install-run-rush.js publish --apply --publish --add-commit-details --include-all --target-branch $CI_COMMIT_REF_NAME --add-commit-details --set-access-level public --registry https://npm-registry.anagolay.network
