retest:
  extends:
    - .install-pnpm-and-node
  stage: test
  needs: ['is-it-pretty', 'changelogs']
  script:
    - !reference [.rush:install, script]
    - !reference [.rush:retest, script]
    - node common/scripts/install-run-rush.js code-quality
