.use-kaniko-base:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  before_script:
    - set -e
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

.use-kaniko:
  extends: .use-kaniko-base
  script:
    - >-
      /kaniko/executor
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${IMAGE_DOCKERFILE_PATH}"
      --destination "${IMAGE_NAME}"

.use-kaniko-with-latest:
  extends: .use-kaniko-base
  script:
    - >-
      /kaniko/executor
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${IMAGE_DOCKERFILE_PATH}"
      --destination "${IMAGE_NAME}"
      --destination "${IMAGE_NAME_LATEST}"

.install-pnpm-and-node:
  before_script:
    - |
      set -e
      curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      pnpm config set store-dir ./common/temp/pnpm-store
      node --version
      pnpm --version
      git --version

.rush:install:
  script:
    - set -e
    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

.rush:change-verify:
  script:
    - !reference [.rush:install, script]
    - set -e
    - echo 'Checking for missing change logs...'
    - node common/scripts/install-run-rush.js change -v

.rush:rebuild:
  script:
    - !reference [.rush:install, script]
    - set -e
    - echo 'Building ...'
    - node common/scripts/install-run-rush.js rebuild --verbose

.rush:build:
  script:
    - !reference [.rush:install, script]
    - set -e
    - echo 'Building ...'
    - node common/scripts/install-run-rush.js build --verbose
