.install-pnpm-and-node:
  before_script:
    - |
      set -e
      curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      pnpm config set store-dir ./common/temp/pnpm-store
      node --version
      pnpm --version
      git --version

.rush:install:
  script:
    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

.rush:change-verify:
  script:
    - echo 'Checking for missing change logs...'
    - node common/scripts/install-run-rush.js change --verify

.rush:rebuild:
  script:
    - echo 'Re-Building ...'
    - node common/scripts/install-run-rush.js rebuild --verbose

.rush:retest:
  script:
    - echo 'Re-Building ...'
    - node common/scripts/install-run-rush.js retest --verbose --production

.rush:build:
  script:
    - echo 'Building ...'
    - node common/scripts/install-run-rush.js build --verbose
